### ISSUE TITLE
Facing this error TypeError both on colab and desktop

### ISSUE THREAD

**Issue by TruthSearchers** [minemo/text-generation-webui-barktts#1]
[```](url)
![Screenshot 2023-04-25 154325](https://user-images.githubusercontent.com/40608534/234248404-5be87430-1acd-47f9-ace5-5a69d47d21d0.jpg)
<

</p>
</details> 
```
Fail.

File "/content/drive/MyDrive/text-generation-webui/modules/extensions.py", line 25, in load_extensions

Traceback (most recent call last): extension.setup() preload_models (text_ckpt_path=f" {model_path}/text.pt", coarse_ckpt_path=f" (model_path)/coarse.pt", fine_ckpt_path=f" (model_path}/fine.pt")

File "/content/drive/MyDrive/text-generation-webui/extensions/bark_tts/script.py", line 85, in setup

TypeError: preload_models() got an unexpected keyword argument 'text_ckpt_path'

 i am facing this issue on both desktop and colab can you tell me what's wrong and how to fix it

**Comment by minemo** [comment]
Hmm seems like Bark changed their way of downloading/saving models.
Fix shouldn't be too difficult, I'll update the script in a sec.

**Comment by minemo** [comment]
Ok, aceb51834a00efbeeab753701079c7d719ef5785 should fix it.
Can you re-download / git pull the newest commit and confirm if it works on your end too?

**Comment by TruthSearchers** [comment]
Yup it's working now , thanks bro :)
