### ISSUE TITLE
 Failed to load the extension "bark_tts".

### ISSUE THREAD

**Issue by swumagic** [minemo/text-generation-webui-barktts#11]
14:56:07-916636 ERROR    Failed to load the extension "bark_tts".
Traceback (most recent call last):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\airj\text-generation-webui\text-generation-webui\extensions\bark_tts\script.py", line 52, in <module>
    streaming_state = shared.args.no_stream
AttributeError: 'Namespace' object has no attribute 'no_stream'

**Comment by LaernuTairos** [comment]
Same. There is no boolean for no stream anymore so this doesn't work, unless it was simply renamed to something else

**Comment by cantodelobo** [comment]
Same
